version: '3.8'

services:
  postgres:
    image: postgres
    volumes:
    - ./01 - Create_table_url.sql:/docker-entrypoint-initdb.d/01 - Create_table_url.sql
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    ports:
    - "5432:5432"